title: "Andrew Singh"
tagline: "Personal blog for machine learning projects"
description: "My blog for personal machine learning projects."
url: "https://andrewsingh.github.io"

# Theme - using gem instead of remote_theme
theme: jekyll-theme-chirpy

# Timezone
timezone: America/Los_Angeles

# Navbar / social (Chirpy reads these)
social:
  name: Andrew Singh
  links:
    - https://github.com/andrewsingh
    - https://www.linkedin.com/in/andrew-singh-ba9615133
