baseURL = "https://andrewsingh.github.io/"
languageCode = "en-us"
title = "Andrew Singh"
theme = "PaperMod"

[params]
  description = "Personal blog for machine learning projects"
  author = "Andrew Singh"

  # Profile mode (home page)
  [params.profileMode]
    enabled = true
    title = "👋 Welcome"
    subtitle = "Hi, I'm Andrew. I'm a machine learning engineer interested in natural language processing, information retrieval, and recommender systems."

    [[params.profileMode.buttons]]
      name = "Posts"
      url = "/posts"

    [[params.profileMode.buttons]]
      name = "Archive"
      url = "/archives"

    [[params.profileMode.buttons]]
      name = "Tags"
      url = "/tags"

  # Social icons
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/andrewsingh"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/andrew-singh-ba9615133"

  [[params.socialIcons]]
    name = "rss"
    url = "/index.xml"

  # Features
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

  # Search
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

# Menu
[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "archives"
  name = "Archive"
  url = "/archives/"
  weight = 20

[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 30

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 40

# Outputs
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Markup settings for math
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    lineNos = false
    noClasses = false
    style = "monokai"
