baseURL = "https://andrewsingh.github.io/"
languageCode = "en-us"
title = "Andrew Singh"
theme = "PaperMod"

[params]
  description = "Personal blog for machine learning projects"
  author = "Andrew Singh"

  # Home info (displayed at top of homepage)
  [params.homeInfoParams]
    Title = "👋 Welcome"
    Content = "Hi, I'm Andrew. I'm a machine learning engineer interested in natural language processing, information retrieval, and recommender systems."

  # Social icons
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/andrewsingh"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/andrew-singh-ba9615133"

  [[params.socialIcons]]
    name = "rss"
    url = "/index.xml"

  # Custom CSS
  [params.assets]
    customCSS = ["css/custom.css"]

  # Features
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

# Menu
[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10

# Outputs
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Markup settings for math
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    lineNos = false
    noClasses = false
    style = "monokai"
